# Generated by Django 3.1 on 2020-08-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre del ejericico')),
                ('description', models.TextField(verbose_name='description')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='fecha creacion')),
                ('out_date', models.DateField(auto_now=True, verbose_name='fecha actualizacion')),
                ('median', models.FloatField(verbose_name='guarda la media')),
                ('mean', models.FloatField(verbose_name='guarda la mediana')),
                ('mode', models.FloatField(verbose_name='guarda la moda')),
                ('trimmed_mean', models.FloatField(verbose_name='guarda media recortada')),
                ('trim_percentage', models.IntegerField(verbose_name='guarda el pocentaje media recortada')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(verbose_name='guarda el dato')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='fecha actualizacion')),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
            ],
        ),
    ]
